services:
  # Backend API Service
  - type: web
    name: maseno-counseling-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: maseno-counseling-db
          property: connectionString

  # PostgreSQL Database
  - type: pserv
    name: maseno-counseling-db
    env: postgresql
    plan: free
    databaseName: maseno_counseling
    databaseUser: maseno_user
